[package]
name = "conveyor"
version = "0.1.0"
edition = "2021"
authors = ["Yoonho Go"]
description = "A TOML-based ETL CLI tool for data pipelines"
license = "MIT"

[dependencies]
# CLI and configuration
clap = { version = "4.5", features = ["derive", "env"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Async runtime
tokio = { version = "1.47", features = ["full"] }
async-trait = "0.1"

# Data processing
polars = { version = "0.44", features = ["lazy", "csv", "json", "parquet"] }
arrow = "54.3"

# HTTP client
reqwest = { version = "0.12", features = ["json", "stream"] }

# Database connectors
mongodb = "3.3"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "mysql", "sqlite"] }

# Error handling
thiserror = "2.0"
anyhow = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Plugin system (will be added later)
# libloading = "0.8"

# Utilities
chrono = { version = "0.4", features = ["serde"] }
regex = "1.11"
indexmap = "2.11"
base64 = "0.22.1"
futures = "0.3.31"

[dev-dependencies]
tempfile = "3.10"
pretty_assertions = "1.4"
