# HTTP Plugin Example (DAG Format)
# This example demonstrates using the HTTP plugin to fetch data from a REST API

[pipeline]
name = "http_plugin_example"
version = "1.0.0"
description = "Example pipeline using HTTP plugin"

[global]
log_level = "info"
max_parallel_tasks = 2
timeout_seconds = 60
plugins = ["http"]  # Load HTTP plugin dynamically

# Stage 1: Fetch users from JSONPlaceholder API
[[stages]]
id = "api_users"
type = "plugin.http"
inputs = []

[stages.config]
url = "https://jsonplaceholder.typicode.com/users"
method = "GET"
format = "json"
timeout = 30

# Stage 2: Output to JSON file
[[stages]]
id = "json_output"
function = "json.write"
inputs = ["api_users"]

[stages.config]
path = "output/users_from_plugin.json"
format = "records"
pretty = true

[error_handling]
strategy = "stop"
