# MongoDB Cursor Pagination with Limit (DAG Format)
# This demonstrates using both cursor pagination and limit

[pipeline]
name = "mongodb_pagination_with_limit"
version = "1.0.0"
description = "Test cursor pagination with limit"

[global]
log_level = "info"
max_parallel_tasks = 2
timeout_seconds = 600
plugins = ["mongodb"]  # Load MongoDB plugin dynamically

# Stage 1: MongoDB Source - First page with limit
[[stages]]
id = "events_limited"
type = "plugin.mongodb"
inputs = []

[stages.config]
connection_string = "mongodb://localhost:27017"
database = "analytics"
collection = "raw_events"
query = '{}'
cursor_field = "_id"
batch_size = 100
limit = 5                     # Only fetch 5 documents
sort = '{ "_id": 1 }'

# Stage 2: Output to stdout
[[stages]]
id = "preview"
type = "sink.stdout"
inputs = ["events_limited"]

[stages.config]
format = "table"

# Error Handling
[error_handling]
strategy = "stop"
