# MongoDB Cursor Pagination Test - Page 2 (DAG Format)
# This pipeline demonstrates fetching the next page using cursor_value

[pipeline]
name = "mongodb_pagination_page2"
version = "1.0.0"
description = "Test cursor-based pagination - page 2"

[global]
log_level = "info"
max_parallel_tasks = 2
timeout_seconds = 600
plugins = ["mongodb"]  # Load MongoDB plugin dynamically

# Stage 1: MongoDB Source - Page 2 (starting after first 8 documents)
[[stages]]
id = "events_page2"
type = "plugin.mongodb"
inputs = []

[stages.config]
connection_string = "mongodb://localhost:27017"
database = "analytics"
collection = "raw_events"
query = '{}'
cursor_field = "_id"
cursor_value = "68ddb46805d95baf344f8805"  # Last _id from previous batch
batch_size = 8
sort = '{ "_id": 1 }'

# Stage 2: Output to stdout
[[stages]]
id = "preview_page2"
type = "sink.stdout"
inputs = ["events_page2"]

[stages.config]
format = "table"

# Error Handling
[error_handling]
strategy = "stop"
