[pipeline]
name = "test-executor-async"
version = "1.0.0"
description = "Test Async executor (Actor pattern)"

[global]
log_level = "info"
executor = "async"
channel_buffer_size = 20

[[stages]]
id = "generate_data"
function = "json.read"
inputs = []

[stages.config]
path = "examples/users.json"

[[stages]]
id = "filter_active"
function = "filter.apply"
inputs = ["generate_data"]

[stages.config]
column = "id"
operator = ">="
value = 5

[[stages]]
id = "display"
function = "stdout.write"
inputs = ["filter_active"]

[stages.config]
format = "table"
limit = 5
