name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - name: macos-x64
            os: macos-latest
            target: x86_64-apple-darwin
            artifact: conveyor-darwin-x64
          - name: macos-arm64
            os: macos-latest
            target: aarch64-apple-darwin
            artifact: conveyor-darwin-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.target }}
          shared-key: "release-cache"
          cache-on-failure: true
          workspaces: "."
          cache-all-crates: true

      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}
        env:
          OPENSSL_STATIC: 1
          OPENSSL_VENDORED: 1

      - name: Prepare artifact
        run: cp target/${{ matrix.platform.target }}/release/conveyor ${{ matrix.platform.artifact }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact }}
          path: ${{ matrix.platform.artifact }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: conveyor-*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
