name: Release Plugins

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v0.11.1)'
        required: true
        type: string

jobs:
  build-plugins-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add WASM target
        run: rustup target add wasm32-wasip2

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Build HTTP Plugin
        run: cargo build --release -p conveyor-plugin-http

      - name: Build MongoDB Plugin
        run: cargo build --release -p conveyor-plugin-mongodb

      - name: Build JS WASM Plugin
        run: cargo build --release -p conveyor-plugin-js-wasm --target wasm32-wasip2

      - name: Generate checksums
        run: |
          cd target/release
          shasum -a 256 libconveyor_plugin_http.dylib > libconveyor_plugin_http.dylib.sha256
          shasum -a 256 libconveyor_plugin_mongodb.dylib > libconveyor_plugin_mongodb.dylib.sha256
          cd ../wasm32-wasip2/release
          shasum -a 256 conveyor_plugin_js_wasm.wasm > conveyor_plugin_js_wasm.wasm.sha256

      - name: Determine release tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Upload plugins to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.tag.outputs.tag }} \
            target/release/libconveyor_plugin_http.dylib \
            target/release/libconveyor_plugin_http.dylib.sha256 \
            target/release/libconveyor_plugin_mongodb.dylib \
            target/release/libconveyor_plugin_mongodb.dylib.sha256 \
            target/wasm32-wasip2/release/conveyor_plugin_js_wasm.wasm \
            target/wasm32-wasip2/release/conveyor_plugin_js_wasm.wasm.sha256 \
            --clobber
